monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        parser:
            level: debug
            type: stream
            path: '%kernel.logs_dir%/dev/parser.log'
            channels: [parser]
    channels: ['parser']
